create table if not exists listing_manual_inputs (
    user_id uuid not null references auth.users(id),
    watchlist_id uuid not null references watchlists(id),
    listing_id uuid not null references l1_listings(id),
    name text,
    search_url text,
    hausgeld_umlagefaehig numeric,
    hausgeld_nicht_umlagefaehig numeric,
    notarkosten numeric,
    grunderwerbssteuer numeric,
    grundbuchkosten numeric,
    mietausfall numeric,
    kaltmiete_pro_qm numeric,
    zielmodus text check (zielmodus in ('nettorendite', 'cashflow')),
    ziel_nettorendite numeric,
    erlaubte_abweichung_nettorendite numeric,
    ziel_cashflow numeric,
    erlaubte_abweichung_cashflow numeric,
    zinssatz numeric,
    tilgungssatz numeric,
    instandhaltung_pro_qm_monat numeric,
    ziel_dscr numeric,
    created_at timestamptz not null default now()
);
